<?xml version="1.0"?>
<robot name="three_axis_arm" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:robo_link name="base_robot_link" radius= "0.05" length="0.03" material="black" mass="0.2"/>
<xacro:robo_link name="link_1" radius= "0.01" length="0.03" material="silver" mass="0.15"/>
<xacro:robo_link name="link_2" radius= "0.01" length="0.15" material="black" mass="0.45" />
<xacro:robo_link name="link_3" radius= "0.01" length="0.15" material="silver" mass="0.05" />
<xacro:box_link name="gripper" sx="0.05" sy="0.05" sz="0.1" material="black" mass="0.1"/>

  
  <!-- <link name="gripper">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.1"/>
      </geometry>
      <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
      <material name="black"/>
    </visual>
  </link>

  <link name="gripper_finger_2">
    <visual>
      <geometry>
        <box size="0.01 0.03 0.03"/>
      </geometry>
      <origin xyz="0.005 0 0.015" rpy="0.0 0.0 0.0"/>
      
      <material name="silver"/>
    </visual>
  </link>

  <link name="gripper_finger_1">
    <visual>
      <geometry>
        <box size="0.01 0.03 0.03"/>
      </geometry>
      <origin xyz="-0.005 0 0.015" rpy="0.0 0.0 0.0"/>
      <material name="silver"/>
    </visual>
  </link> -->

  <!-- Joints and Links -->
  <!-- Joint 1 -->

  <joint name="joint_1" type="revolute">
    <parent link="base_robot_link"/>
    <child link="link_1"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="1.0"/>
  </joint>
  <!-- Joint 2 -->
  <joint name="joint_2" type="revolute">
    <parent link="link_1"/>
    <child link="link_2"/>
    <origin xyz="0 -0.02 0.025" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>
  <!-- Joint 3 -->
  <joint name="joint_3" type="revolute">
    <parent link="link_2"/>
    <child link="link_3"/>
    <origin xyz="0 0.02 0.15" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>
  <!-- Gripper -->
  <joint name="gripper_joint" type="revolute">
    <parent link="link_3"/>
    <child link="gripper"/>
    <origin xyz="0.0 -0.01 0.15" rpy="1.57 0.0 3.14"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>


      <joint name = "robo_base_joint" type = "fixed">
        <parent link="base_link"/>
        <child link="base_robot_link"/>
        <origin xyz="${base_length/2.0} 0 0" rpy="0 0 0" />

    </joint>
  <!-- End Effector -->

</robot>
